"""empty message

Revision ID: 208a05530e61
Revises: 27f1dd1dcc9f
Create Date: 2019-11-23 12:33:28.017572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '208a05530e61'
down_revision = '27f1dd1dcc9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('terms', sa.Column('description', sa.String(length=128), nullable=True))
    op.add_column('terms', sa.Column('tweet_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('terms', 'tweet_count')
    op.drop_column('terms', 'description')
    # ### end Alembic commands ###
