"""create db

Revision ID: 37859257bce7
Revises: 
Create Date: 2019-11-20 14:26:36.155505

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '37859257bce7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=64), nullable=True),
    sa.Column('processing_status', postgresql.ENUM('pending', 'processing', 'done', name='processing_status'), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=True),
    sa.Column('words', postgresql.ARRAY(sa.String(length=32)), nullable=True),
    sa.Column('polarity', sa.Float(), nullable=True),
    sa.Column('anger_percentage', sa.Float(), nullable=True),
    sa.Column('fear_percentage', sa.Float(), nullable=True),
    sa.Column('joy_percentage', sa.Float(), nullable=True),
    sa.Column('sad_percentage', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topics')
    op.drop_table('terms')
    # ### end Alembic commands ###
