"""empty message

Revision ID: 60304402eeb5
Revises: 208a05530e61
Create Date: 2019-11-23 14:19:58.411786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60304402eeb5'
down_revision = '208a05530e61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('terms', sa.Column('anger', sa.Integer(), nullable=True))
    op.add_column('terms', sa.Column('fear', sa.Integer(), nullable=True))
    op.add_column('terms', sa.Column('joy', sa.Integer(), nullable=True))
    op.add_column('terms', sa.Column('sadness', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('terms', 'sadness')
    op.drop_column('terms', 'joy')
    op.drop_column('terms', 'fear')
    op.drop_column('terms', 'anger')
    # ### end Alembic commands ###
