"""empty message

Revision ID: 8e3277268e47
Revises: 60304402eeb5
Create Date: 2019-11-23 14:21:51.625824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e3277268e47'
down_revision = '60304402eeb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('terms', sa.Column('polarity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('terms', 'polarity')
    # ### end Alembic commands ###
